"""Voice briefing: a short spoken summary of one pair, read aloud by ElevenLabs text-to-speech.

The script is built only from verified data (tier, measured distances, dates with their source pages), never
generated by a language model, so the voice cannot say anything the app cannot cite. The API key stays on the
server; the browser only ever receives audio bytes.
"""
import datetime as dt
import json
import os
import re
from collections import OrderedDict
from urllib.request import Request, urlopen

from engine.tiers import TIER_LABELS

API_URL = "https://api.elevenlabs.io/v1/text-to-speech/{voice}?output_format=mp3_44100_128"
DEFAULT_VOICE_ID = "JBFqnCBsd6RMkjVDRZzb"  # "George", a premade ElevenLabs voice
DEFAULT_MODEL_ID = "eleven_flash_v2_5"  # low latency, fits a serverless request
TIMEOUT_S = 20  # below the 30 s serverless limit in vercel.json
MAX_CHARS = 1200
CACHE_SIZE = 64
UTILITY = {"DESC": "Dominion Energy South Carolina", "GPC": "Georgia Power"}
SOURCE = {"desc-2428": "DESC's 2024 to 2028 project list", "gpc-irp25-v3": "Georgia Power's 2025 resource plan"}
TIMING = {
    "same_window": "Their build windows overlap by {overlap} days.",
    "within_1y": "Their in-service dates are {gap} days apart, within a year of each other.",
    "separate": "Their in-service dates are {gap} days apart, so their timing is separate.",
}

_cache: OrderedDict[tuple, bytes] = OrderedDict()


def api_key() -> str | None:
    return (os.environ.get("ELEVENLABS_API_KEY") or "").strip() or None


def voice_id() -> str:
    return os.environ.get("ELEVENLABS_VOICE_ID", DEFAULT_VOICE_ID)


def model_id() -> str:
    return os.environ.get("ELEVENLABS_MODEL_ID", DEFAULT_MODEL_ID)


def clear_cache() -> None:
    _cache.clear()


def speakable(name: str) -> str:
    """Plan shorthand read aloud: 'SAV: A - B #5 115KV' -> 'A to B number 5 115 kilovolt'."""
    text = re.sub(r"^[A-Z]{2,5}:\s*", "", name)
    text = re.sub(r"\s+[-–]\s+", " to ", text)
    text = re.sub(r"#\s*(\d+)", r"number \1", text)
    text = re.sub(r"(\d+)\s*kV\b", r"\1 kilovolt", text, flags=re.IGNORECASE)
    return re.sub(r"\s+", " ", text).strip()


def _date(iso: str) -> str:
    day = dt.date.fromisoformat(iso)
    return f"{day:%B} {day.day}, {day.year}"


def _cited_date(project: dict) -> str:
    kind = "a need date" if project["utility"] == "GPC" else "an in-service date"
    page = project.get("in_service_page") or project["page"]
    source = SOURCE.get(project["source_id"], project["source_id"])
    when = _date(project["in_service_date"])
    return f"{UTILITY[project['utility']]} lists {kind} of {when}, on page {page} of {source}."


def brief_script(detail: dict) -> str:
    a, b = detail["project_a"], detail["project_b"]
    tier = detail["tier"]
    tier_line = f"Tier {tier}: {TIER_LABELS[tier].lower()}." if tier else "Beyond the 25 mile tier table."
    where = ("The two projects touch at a shared facility." if detail["touching"]
             else f"At their closest points they are {detail['dist_closest_mi']:.2f} miles apart.")
    parts = [
        f"GridPulse briefing. Pair {detail['rank']} in the Savannah and Augusta study. {tier_line}",
        f"{UTILITY[a['utility']]}'s {speakable(a['name'])}, and {UTILITY[b['utility']]}'s {speakable(b['name'])}.",
        f"{where} Measured center to center, Sperry's method, they are {detail['dist_center_mi']:.2f} miles apart.",
        TIMING[detail["timeline_label"]].format(overlap=detail.get("window_overlap_days") or 0,
                                                gap=detail["in_service_gap_days"]),
        _cited_date(a),
        _cited_date(b),
        "This is a candidate for human review, not a decision.",
    ]
    return " ".join(parts)[:MAX_CHARS]


def upstream_reason(body: bytes) -> str | None:
    """ElevenLabs' short error status (e.g. 'missing_permissions'), safe to show: only [a-z_] words pass."""
    try:
        detail = json.loads(body).get("detail")
    except (ValueError, AttributeError):
        return None
    status = detail.get("status") if isinstance(detail, dict) else None
    return status if isinstance(status, str) and re.fullmatch(r"[a-z_]{1,40}", status) else None


class VoiceError(Exception):
    """ElevenLabs could not produce audio; the message is safe to show (never contains the key)."""


def synthesize(text: str) -> bytes:
    key = api_key()
    if key is None:
        raise VoiceError("voice briefing is not configured")
    cache_key = (voice_id(), model_id(), text)
    if cache_key in _cache:
        _cache.move_to_end(cache_key)
        return _cache[cache_key]
    request = Request(API_URL.format(voice=voice_id()), method="POST",
                      data=json.dumps({"text": text, "model_id": model_id()}).encode(),
                      headers={"xi-api-key": key, "Content-Type": "application/json", "Accept": "audio/mpeg"})
    with urlopen(request, timeout=TIMEOUT_S) as response:
        audio = response.read()
    _cache[cache_key] = audio
    if len(_cache) > CACHE_SIZE:
        _cache.popitem(last=False)
    return audio
